name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Format (black --check)
        run: black --check .
      - name: Lint (ruff)
        run: ruff check .
      - name: Types (mypy)
        run: mypy .
      - name: Unit tests
        run: pytest -q
      - name: Acceptance tests
        run: pytest -q tests/acceptance
      - name: Coverage
        run: pytest --cov=src --cov-report=term-missing --cov-fail-under=85
      - name: Build package
        run: python -m build
      - name: Security (pip-audit)
        run: pip-audit
      # optional Bandit
      # - name: Security (bandit)
      #   run: bandit -r src -ll

